# game.py_catch-up